-- 코드를 작성해주세요
SELECT
    gen3.ID
FROM ECOLI_DATA AS gen1
JOIN ECOLI_DATA AS gen2
ON gen2.PARENT_ID = gen1.ID
JOIN ECOLI_DATA AS gen3
ON gen3.PARENT_ID = gen2.ID
WHERE gen1.PARENT_ID IS NULL
ORDER BY gen3.ID ASC;