-- 코드를 작성해주세요
SELECT
    i.ITEM_ID,
    i.ITEM_NAME,
    i.RARITY
FROM ITEM_INFO i
WHERE NOT EXISTS (
    SELECT 1
    FROM ITEM_TREE t
    WHERE t.PARENT_ITEM_ID = i.ITEM_ID
)
ORDER BY i.ITEM_ID DESC;
    