-- 코드를 입력하세요
SELECT
    YEAR(o.SALES_DATE) AS YEAR,
    MONTH(o.SALES_DATE) AS MONTH,
    u.GENDER,
    COUNT(DISTINCT u.USER_ID) AS USERS
FROM USER_INFO u
JOIN ONLINE_SALE o
    ON u.USER_ID = o.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY MONTH(o.SALES_DATE),u.GENDER
ORDER BY
    YEAR(o.SALES_DATE) ASC,
    MONTH(o.SALES_DATE) ASC,
    u.GENDER ASC;