-- 코드를 입력하세요
WITH RENTAL_INFO AS(
    SELECT
        CAR_ID,
        DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT
    CAR_ID,
    ROUND(AVG(RENTAL_DATE), 1) AS AVERAGE_DURATION
FROM RENTAL_INFO
GROUP BY CAR_ID
HAVING AVG(RENTAL_DATE) >= 7
ORDER BY
    AVERAGE_DURATION DESC,
    CAR_ID DESC;
    