-- 코드를 입력하세요
SELECT
    m.MEMBER_NAME,
    r.REVIEW_TEXT,
    r.REVIEW_DATE
FROM MEMBER_PROFILE m
JOIN REST_REVIEW r
    ON m.MEMBER_ID = r.MEMBER_ID
WHERE r.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    WHERE MEMBER_ID IS NOT NULL
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY
    r.REVIEW_DATE ASC,
    r.REVIEW_TEXT ASC;