-- 코드를 작성해주세요
SELECT
    i.ID,
    n.FISH_NAME,
    i.LENGTH
FROM FISH_INFO AS i
JOIN FISH_NAME_INFO AS n
ON i.FISH_TYPE = n.FISH_TYPE
JOIN (
    SELECT
        FISH_TYPE,
        MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE) AS m
ON i.FISH_TYPE = m.FISH_TYPE
    AND i.LENGTH = m.MAX_LENGTH
ORDER BY i.ID ASC;
